sonar.projectKey=Onesiforus-Rade-Putra_CoT-Prompting
sonar.organization=onesiforus-rade-putra
sonar.host.url=https://sonarcloud.io

sonar.projectName=CoT-Prompting
sonar.sourceEncoding=UTF-8

sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=test/**/*

sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.gr.dart,**/generated/**,build/**,.dart_tool/**